<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Downloader"/>
        <PackageReference Include="FluentIcons.Avalonia"/>
        <PackageReference Include="MonoTorrent"/>
        <PackageReference Include="Xunlei.Open.DlSdk" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.linux-x64" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.osx-universal" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.win-x64" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.win-x86" />
    </ItemGroup>

</Project>
