<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <!--If you are willing to use platform-specific APIs, use conditional compilation.
        See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
        <TargetFramework>net10.0</TargetFramework>
        <ApplicationIcon>../BoolDownload/Assets/avalonia-logo.ico</ApplicationIcon>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Downloader" />
        <PackageReference Include="FluentIcons.Resources.Avalonia" />
        <PackageReference Include="Xunlei.Open.DlSdk" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.linux-x64" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.osx-universal" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.win-x64" />
        <PackageReference Include="Xunlei.Open.DlSdk.Native.win-x86" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BoolDownload\BoolDownload.csproj"/>
    </ItemGroup>

</Project>
