; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7EA4BC15-9C2A-4214-9906-8186070BDE6E}
AppName=BoollDownload
AppVersion=1.1.0
;AppVerName={cm:NameAndVersion,BoollDownload,1.0}
AppPublisher=Superiot, Inc.
AppPublisherURL=http://www.10qu.com/
AppSupportURL=http://www.10qu.com/
AppUpdatesURL=http://www.10qu.com/
DefaultDirName={autopf}\BoollDownload
UninstallDisplayIcon={app}\BoolDownload.Desktop.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\project\bool-download\installer\output
OutputBaseFilename=bool_download_setup
SolidCompression=yes
WizardStyle=modern windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\project\bool-download\BoolDownload.Desktop\bin\Release\net10.0\win-x64\publish\BoolDownload.Desktop.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project\bool-download\BoolDownload.Desktop\bin\Release\net10.0\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\BoollDownload"; Filename: "{app}\BoolDownload.Desktop.exe"
Name: "{autodesktop}\BoollDownload"; Filename: "{app}\BoolDownload.Desktop.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\BoolDownload.Desktop.exe"; Description: "{cm:LaunchProgram,BoollDownload}"; Flags: nowait postinstall skipifsilent

